# Generated by Django 3.2 on 2021-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210722_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
