# Generated by Django 3.2 on 2021-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shoppingcart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituretype',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
