# Generated by Django 3.2 on 2021-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_furnituretype_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituretype',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
