# Generated by Django 3.2 on 2021-08-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_furnituretype_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='url1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='furniture',
            name='url2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='furniture',
            name='url3',
            field=models.URLField(blank=True, default=''),
        ),
    ]
