# Generated by Django 3.2 on 2021-08-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210803_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='address',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='store.useraddress'),
        ),
    ]
