# Generated by Django 3.2 on 2021-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_shoppingcart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
